import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer/footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Chatbot from "@/components/chatbot/chatbox";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Active",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
          {/* Contenido principal */}
          <main className="flex-grow">{children}</main>

          {/* Botón de chat flotante */}
          <Chatbot />  {/* Colocamos el chat flotante aquí */}

          {/* Footer siempre al final */}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}